version: "3"
services:

  composer:
      image: composer:latest
  mysql:
      image: mysql:latest
      command: --default-authentication-plugin=mysql_native_password
      volumes:
      - mysql:/var/lib/mysql
      container_name: mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
      ports:
        - 3306:3306

volumes:
  mysql: